import{createGame,W,H}from './game-engine.mjs?v=6';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),score=document.getElementById('score'),status=document.getElementById('game-status'),start=document.getElementById('start-game'),pause=document.getElementById('pause-game');
const meta={dino:['Dino Run','Press Space, ↑ or Jump to leap over obstacles. Keep running for a higher score.'],catch:['Photon Catch','Move with ← → or A / D to catch falling photons. You have three lives.'],snake:['Snake','Arrow keys or WASD to steer. Collect the dots without hitting a wall or yourself.'],breaker:['Photon breaker','Move with ← → or A / D. Bounce the light into all the bricks. You have three lives.'],stack:['Stack lab','Press Space or Drop to place a moving block. Only the overlapping part stays. Stack 30 layers to win.'],aliens:['Alien shooter','Move with ← → or A / D. Hold Space or Fire to shoot. Clear three waves before the aliens reach you.']};
let type='snake',g=createGame(type),running=false,paused=false,last=0,keys={};
const clearKeys=()=>{keys={};};
function choose(t){type=t;g=createGame(t);running=false;paused=false;clearKeys();document.querySelectorAll('[data-game]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.game===t)));document.getElementById('game-title').textContent=meta[t][0];document.getElementById('instructions').textContent=meta[t][1];canvas.setAttribute('aria-label',meta[t][0]+'. '+meta[t][1]);start.textContent='Start game';pause.textContent='Pause';pause.disabled=true;status.textContent='Ready when you are.';document.getElementById('action-control').textContent=t==='stack'?'Drop':t==='aliens'?'Fire':t==='dino'?'Jump':'Action';document.getElementById('action-control').disabled=!['stack','aliens','dino'].includes(t);document.querySelectorAll('[data-control="up"],[data-control="down"]').forEach(b=>b.hidden=t!=='snake');document.querySelectorAll('[data-control="left"],[data-control="right"]').forEach(b=>b.hidden=['stack','dino'].includes(t));draw();}
document.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.game)));
start.addEventListener('click',()=>{g=createGame(type);running=true;paused=false;clearKeys();last=performance.now();start.textContent='Restart';pause.disabled=false;pause.textContent='Pause';status.textContent='Playing '+meta[type][0]+'.';canvas.focus({preventScroll:true});});
function togglePause(){if(!running||g.over)return;paused=!paused;clearKeys();pause.textContent=paused?'Resume':'Pause';status.textContent=paused?'Paused.':'Playing '+meta[type][0]+'.';draw();}
pause.addEventListener('click',togglePause);
function input(k){if(running&&!paused&&!g.over)g.input(k);}
const map={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down',' ':'action'};
document.addEventListener('keydown',e=>{if(!document.querySelector('.game-panel').contains(document.activeElement))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(key==='p'){e.preventDefault();if(!e.repeat)togglePause();return;}const k=map[key];if(!k)return;if(e.target.tagName==='BUTTON'&&key===' ')return;e.preventDefault();keys[k]=true;if(!e.repeat)input(k);});
document.addEventListener('keyup',e=>{const k=map[e.key.toLowerCase?.()]||map[e.key];if(k)keys[k]=false;});
document.querySelectorAll('[data-control]').forEach(b=>{const k=b.dataset.control;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[k]=true;input(k);});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys[k]=false);b.addEventListener('click',e=>{if(e.detail===0)input(k);});});
window.addEventListener('blur',()=>{clearKeys();if(running&&!paused)togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearKeys();if(running&&!paused)togglePause();}});
function rect(x,y,w,h,color='#ddd'){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);}function dot(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function draw(){rect(0,0,W,H,'#1c1c1e');ctx.strokeStyle='#2c2c2f';ctx.lineWidth=1;for(let x=0;x<W;x+=20){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}
if(type==='snake'){g.snake.forEach((s,i)=>rect(s.x*20+2,s.y*20+2,16,16,i?'#919195':'#fafafa'));dot(g.food.x*20+10,g.food.y*20+10,6,'#eee');}
if(type==='breaker'){g.bricks.forEach((b,i)=>rect(b.x,b.y,b.w,b.h,['#777','#999','#ccc'][i%3]));rect(g.paddle,H-30,100,9);dot(g.ball.x,g.ball.y,7,'#fff');ctx.fillStyle='#aaa';ctx.font='13px system-ui';ctx.fillText('Lives '+g.lives,18,H-8);}
if(type==='stack'){g.blocks.forEach((b,i)=>rect(b.x,b.y,b.w,20,i%2?'#999':'#ddd'));rect(g.moving.x,g.moving.y,g.moving.w,20,'#fff');}
if(type==='aliens'){for(const e of g.enemies){rect(e.x-14,e.y-9,28,18,'#aaa');rect(e.x-10,e.y-13,5,5);rect(e.x+5,e.y-13,5,5);rect(e.x-9,e.y-3,5,5,'#222');rect(e.x+4,e.y-3,5,5,'#222');}for(const b of g.bullets)rect(b.x-2,b.y,4,12,'#fff');ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(g.ship,H-42);ctx.lineTo(g.ship-16,H-18);ctx.lineTo(g.ship+16,H-18);ctx.fill();ctx.font='13px system-ui';ctx.fillText('Wave '+g.wave,18,H-8);}
if(type==='dino'){rect(0,360,W,2,'#777');rect(80,g.y-27,27,27);rect(97,g.y-43,24,22);rect(114,g.y-37,3,3,'#222');rect(72,g.y-22,12,8);rect(82,g.y,7,9);rect(100,g.y,7,9);for(const o of g.obstacles){rect(o.x,360-o.h,o.w,o.h,'#aaa');rect(o.x-5,366-o.h,6,o.h/2,'#aaa');}for(let i=0;i<8;i++)rect((i*100-g.distance*7)%700,382,22,2,'#555');}
if(type==='catch'){rect(g.paddle,382,90,10);for(const d of g.drops){dot(d.x,d.y,13,'#555');dot(d.x,d.y,6,'#fff');}ctx.fillStyle='#bbb';ctx.font='14px system-ui';ctx.fillText('Lives '+g.lives,18,H-8);}
score.textContent=String(g.score);if(!running||paused||g.over){rect(0,0,W,H,'rgba(0,0,0,.48)');ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='26px system-ui';ctx.fillText(g.over?(g.won?'Well played!':'Game over'):paused?'Paused':'Ready to play?',W/2,H/2);ctx.font='15px system-ui';ctx.fillText(g.over?'Press Restart for another round':paused?'Press Resume to continue':'Choose Start game above',W/2,H/2+32);ctx.textAlign='left';}}
function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;if(running&&!paused&&!g.over){g.update(dt,keys);if(g.over){pause.disabled=true;status.textContent=(g.won?'You won! ':'Game over. ')+'Final score: '+g.score+'. Press Restart to try again.';clearKeys();}}draw();requestAnimationFrame(frame);}choose('snake');requestAnimationFrame(frame);
